pipeline {
   agent any

   stages {
      stage('pull code') {
         steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/HePeng11/hellowold_jenkins']]])
         }
      }
      stage('build code') {
         steps {
           sh label: '', script: 'mvn clean package'
         }
      }
      stage('publish project') {
         steps {
            deploy adapters: [tomcat9(credentialsId: 'tomcat-manage', path: '', url: 'http://122.51.222.178/')], contextPath: null, war: 'target/*.war'
         }
      }
   }
}
